# Generated by Django 4.1.7 on 2023-08-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Richest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('net_worth', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
